// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  moonContainer: string;
  moon: string;
  imageContainer: string;
  profilePicture: string;
  moonsContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
